import Head from "next/head";
import { useState } from "react";
import { BiExit, BiUserPlus } from "react-icons/bi";
import Form from "../components/Form";
import Table from "../components/Table";

export default function Home() {
  const [visible, setVisible] = useState(false);

  const buttonClass = () => {
    let classes = 'flex text-white px-4 py-2 border rounded-md hover:bg-grary-50 hover:border-indigo-500 hover:text-gray-800 ';
    return classes += (visible) ? 'bg-red-500' : 'bg-indigo-500';
  }

  return (
    <section>
      <Head>
        <title>CRUD Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='py-5'>
        <h1 className='text-xl md:text-5xl text-center font-bold py-10'>Full Stack CRUD App</h1>

        <div className="container mx-auto flex justify-between py-5">
          <div className="left flex gap-3">
            <button
              onClick={() => setVisible(!visible)}
              className={buttonClass()}>
              {visible ? "Close" : "Add"} <span className='px-1'>{visible ? <BiExit size={23} /> : <BiUserPlus size={23} />}</span>
            </button>
          </div>
        </div>

        <div className="container mx-auto">
          {visible && <Form />}
        </div>

        <div className="container mx-auto mt-5 md:my-5">
          <Table />
        </div>

      </main>
    </section>
  )
}
