import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>CRUD Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <h1 className="text-3xl font-bold underline">
          Hello world!
        </h1>
        <div className="container">
          <p>test</p>
        </div>
      </main>
    </div>
  )
}
